"""add process_events

Revision ID: 17f7bc186e29
Revises: ff26d4560768
Create Date: 2026-02-02 18:05:32.856938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17f7bc186e29'
down_revision: Union[str, Sequence[str], None] = 'ff26d4560768'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_logs_client_id'), table_name='email_logs')
    op.drop_index(op.f('ix_email_logs_id'), table_name='email_logs')
    op.drop_index(op.f('ix_email_logs_office_id'), table_name='email_logs')
    op.drop_index(op.f('ix_email_logs_process_id'), table_name='email_logs')
    op.drop_table('email_logs')
    op.drop_index(op.f('ix_process_events_created_at'), table_name='process_events')
    op.drop_index(op.f('ix_process_events_id'), table_name='process_events')
    op.drop_index(op.f('ix_process_events_office_id'), table_name='process_events')
    op.drop_index(op.f('ix_process_events_office_process_created'), table_name='process_events')
    op.drop_index(op.f('ix_process_events_process_id'), table_name='process_events')
    op.drop_index(op.f('ix_process_events_type'), table_name='process_events')
    op.drop_table('process_events')
    op.drop_index(op.f('ix_email_flows_office_id'), table_name='email_flows')
    op.drop_index(op.f('ix_email_flows_process_id'), table_name='email_flows')
    op.drop_table('email_flows')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_flows',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('office_id', sa.INTEGER(), nullable=False),
    sa.Column('process_id', sa.INTEGER(), nullable=False),
    sa.Column('active', sa.BOOLEAN(), server_default=sa.text('1'), nullable=False),
    sa.Column('interval_days', sa.INTEGER(), server_default=sa.text("'3'"), nullable=False),
    sa.Column('max_attempts', sa.INTEGER(), server_default=sa.text("'10'"), nullable=False),
    sa.Column('attempts', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('last_sent_at', sa.DATETIME(), nullable=True),
    sa.Column('template', sa.VARCHAR(), server_default=sa.text("'cobranca_docs'"), nullable=False),
    sa.Column('stop_on_any_upload', sa.BOOLEAN(), server_default=sa.text('1'), nullable=False),
    sa.Column('stopped_reason', sa.VARCHAR(), nullable=True),
    sa.Column('stopped_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['office_id'], ['offices.id'], ),
    sa.ForeignKeyConstraint(['process_id'], ['processes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_flows_process_id'), 'email_flows', ['process_id'], unique=False)
    op.create_index(op.f('ix_email_flows_office_id'), 'email_flows', ['office_id'], unique=False)
    op.create_table('process_events',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('office_id', sa.INTEGER(), nullable=False),
    sa.Column('process_id', sa.INTEGER(), nullable=False),
    sa.Column('type', sa.VARCHAR(length=64), nullable=False),
    sa.Column('title', sa.VARCHAR(length=160), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['office_id'], ['offices.id'], ),
    sa.ForeignKeyConstraint(['process_id'], ['processes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_process_events_type'), 'process_events', ['type'], unique=False)
    op.create_index(op.f('ix_process_events_process_id'), 'process_events', ['process_id'], unique=False)
    op.create_index(op.f('ix_process_events_office_process_created'), 'process_events', ['office_id', 'process_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_process_events_office_id'), 'process_events', ['office_id'], unique=False)
    op.create_index(op.f('ix_process_events_id'), 'process_events', ['id'], unique=False)
    op.create_index(op.f('ix_process_events_created_at'), 'process_events', ['created_at'], unique=False)
    op.create_table('email_logs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('office_id', sa.INTEGER(), nullable=False),
    sa.Column('process_id', sa.INTEGER(), nullable=True),
    sa.Column('client_id', sa.INTEGER(), nullable=True),
    sa.Column('to_email', sa.VARCHAR(), nullable=False),
    sa.Column('subject', sa.VARCHAR(), nullable=False),
    sa.Column('body', sa.TEXT(), nullable=False),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.Column('error', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['office_id'], ['offices.id'], ),
    sa.ForeignKeyConstraint(['process_id'], ['processes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_logs_process_id'), 'email_logs', ['process_id'], unique=False)
    op.create_index(op.f('ix_email_logs_office_id'), 'email_logs', ['office_id'], unique=False)
    op.create_index(op.f('ix_email_logs_id'), 'email_logs', ['id'], unique=False)
    op.create_index(op.f('ix_email_logs_client_id'), 'email_logs', ['client_id'], unique=False)
    # ### end Alembic commands ###
