"""add documents and drive_folder_id

Revision ID: 51e38aaa538b
Revises: 
Create Date: 2026-01-25 22:32:06.432515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51e38aaa538b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('office_id', sa.Integer(), nullable=False),
    sa.Column('process_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=True),
    sa.Column('drive_file_id', sa.String(), nullable=False),
    sa.Column('drive_web_view_link', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['office_id'], ['offices.id'], ),
    sa.ForeignKeyConstraint(['process_id'], ['processes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_drive_file_id'), 'documents', ['drive_file_id'], unique=False)
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_index(op.f('ix_documents_office_id'), 'documents', ['office_id'], unique=False)
    op.create_index(op.f('ix_documents_process_id'), 'documents', ['process_id'], unique=False)
    op.add_column('processes', sa.Column('drive_folder_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_processes_drive_folder_id'), 'processes', ['drive_folder_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_processes_drive_folder_id'), table_name='processes')
    op.drop_column('processes', 'drive_folder_id')
    op.drop_index(op.f('ix_documents_process_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_office_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_drive_file_id'), table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
